### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (10x100 and 768x100)

### ISSUE THREAD

**Issue by TrivenDev** [TsingZ0/HtFLlib#3]
nohup python -u main.py -t 1 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 100 -data Cifar100 -m HtM10 -fd 512 -did 0 -algo LG-FedAvg > total-Cifar100-HtM10-fd=512-LG-FedAvg.out 2>&1 &

nohup python -u main.py -t 1 -ab 1 -lr 0.01 -jr 1 -lbs 10 -ls 1 -nc 20 -nb 100 -data Cifar100 -m HtM10 -fd 512 -did 0 -algo FedGH -slr 0.01 -se 1 > total-Cifar100-HtM10-fd=512-FedGH.out 2>&1 &

The following problems may occur when running the above methods:
What is going on? I don't know if the problem is in the code of ResNet.   

```
============= Running time: 0th =============
Creating server and clients ...
FedAvgCNN(in_features=3, num_classes=args.num_classes, dim=1600)
torchvision.models.googlenet(pretrained=False, aux_logits=False, num_classes=args.num_classes)
mobilenet_v2(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet18(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet34(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet50(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet101(pretrained=False, num_classes=args.num_classes)
torchvision.models.resnet152(pretrained=False, num_classes=args.num_classes)
torchvision.models.vit_b_16(image_size=32, num_classes=args.num_classes)
torchvision.models.vit_b_32(image_size=32, num_classes=args.num_classes)

Join ratio / total clients: 1.0 / 20
Finished creating server and clients.

-------------Round number: 0-------------

Evaluate heterogeneous models
Client 0: Acc: 0.0, AUC: 0.46576140777096875
Client 1: Acc: 0.0, AUC: 0.4221138082394627
Client 2: Acc: 0.002902757619738752, AUC: 0.5628233757461241
Client 3: Acc: 0.0, AUC: 0.37111092897915604
Client 4: Acc: 0.004545454545454545, AUC: 0.5936408158722208
Client 5: Acc: 0.05416666666666667, AUC: 0.5672693758573388
Client 6: Acc: 0.04487179487179487, AUC: 0.4602739342803445
Client 7: Acc: 0.0, AUC: 0.39070815936244674
Traceback (most recent call last):
  File "D:\���д���\HtFL\system\main.py", line 407, in <module>
    run(args)
  File "D:\���д���\HtFL\system\main.py", line 276, in run
    server.train()  # START FL Training!!
  File "D:\���д���\HtFL\system\flcore\servers\serverlg.py", line 37, in train
    self.evaluate()
  File "D:\���д���\HtFL\system\flcore\servers\serverbase.py", line 203, in evaluate
    stats = self.test_metrics()  # return (ids, num_samples, tot_correct, tot_auc)
  File "D:\���д���\HtFL\system\flcore\servers\serverbase.py", line 178, in test_metrics
    ct, ns, auc = c.test_metrics()  # check accuracy for single client
  File "D:\���д���\HtFL\system\flcore\clients\clientbase.py", line 87, in test_metrics
    output = model(x)  # logits not softmax
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\���д���\HtFL\system\flcore\trainmodel\models.py", line 51, in forward
    out = self.head(out)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\container.py", line 219, in forward
    input = module(input)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\DevTools\anaconda3\envs\htfl\lib\site-packages\torch\nn\modules\linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x100 and 768x100)

```

**Comment by TsingZ0** [comment]
LG-FedAvg and FedGH belong to "Partial-heterogeneity-based HtFL methods", which require some part of the models to be homogeneous, thus not applicable when using HtM10 (including ResNets and ViTs). 

Please check our papers [FedTGP](https://arxiv.org/abs/2401.03230) and [FedKTL](https://arxiv.org/abs/2403.15760) for more details.
